/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sgTuDNrhQXz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"
import { useState } from "react";
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Button } from "@/components/ui/button"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"

export function Todolist() {

  /* const addTask = () => {
    if (newTask.trim() !== '') {
      setTasks([...tasks, newTask]);
      setNewTask('');
    }
  }; */

  return (
    <div className="mx-auto max-w-md space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Todo List</h1>
        <p className="text-gray-500 dark:text-gray-400">Please fill in the form to add a new task</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="task">Task</Label>
          <Input id="task" placeholder="Enter your task" required value={newTask} onChange={(e) => setNewTask(e.target.value)}  />
        </div>
        <div className="space-y-2">
          <Label htmlFor="priority">Priority</Label>
          <RadioGroup id="priority" defaultValue="low" className="flex items-center gap-2">
            <Label htmlFor="priority-low" className="flex items-center gap-2 font-normal">
              <RadioGroupItem id="priority-low" value="low" /> Low
            </Label>
            <Label htmlFor="priority-medium" className="flex items-center gap-2 font-normal">
              <RadioGroupItem id="priority-medium" value="medium" /> Medium
            </Label>
            <Label htmlFor="priority-high" className="flex items-center gap-2 font-normal">
              <RadioGroupItem id="priority-high" value="high" /> High
            </Label>
          </RadioGroup>
        </div>
        <Button onClick={addTask} type="submit" className="w-full">
          Add Task
        </Button>
      </div>
    </div>
  )
}
